apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipblock-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipblock-operator
  template:
    metadata:
      labels:
        app: ipblock-operator
    spec:
      serviceAccountName: controller-manager
      containers:
        - name: operator
          image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command:
            - /manager

